## Pandas

In [1]:
import pandas  as pd
import numpy as np

In [2]:
x = [3,5,6,7,9,5,2]

var = pd.Series(x)

print(var)
print(type(var))

0    3
1    5
2    6
3    7
4    9
5    5
6    2
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [4]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [5]:
df.to_csv("TestingData.csv")

In [6]:
df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [7]:
type(df.loc["Row1"])

pandas.core.series.Series

In [8]:
df.iloc[:,1:].values.shape

(5, 3)

In [9]:
df = pd.read_csv("AiTrends.csv", usecols = ["job_id","job_title"])
df.tail()

       job_id                  job_title
10340   10341              Data Engineer
10341   10342               Data Analyst
10342   10343  Machine Learning Engineer
10343   10344              Data Engineer
10344   10345                AI Engineer

In [10]:
df.describe()

             job_id
count  10345.000000
mean    5173.000000
std     2986.488601
min        1.000000
25%     2587.000000
50%     5173.000000
75%     7759.000000
max    10345.000000

In [11]:
data = np.arange(0,20).reshape(5,4)
df = pd.DataFrame(
    data,
    index = ["Row1","Row2","Row3","Row4","Row5"],
    columns = ["Col1","Col2","Col3","Col4"]
)
print(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [12]:
df.iloc[0:2,0:3]

      Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6

In [13]:
df["Col1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int64

In [14]:
df[["Col1"]]

      Col1
Row1     0
Row2     4
Row3     8
Row4    12
Row5    16

In [15]:
df.loc["Row1"]

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [16]:
df.iloc[2]

Col1     8
Col2     9
Col3    10
Col4    11
Name: Row3, dtype: int64

In [17]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Read Json to CSC

In [18]:
df = pd.read_csv("TestingData.csv")
df.head

<bound method NDFrame.head of   Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19>

In [19]:
Data = {
    "Student" : ["Aman","Shardha","Raghav","Alakh","Striver","Kunal","Khan"],
"Age" : [30,28,26,35,45,76,98],
"Marks" : [95,90,60,97,45,87,97]
}
df = pd.DataFrame(Data)
df.to_csv("Student.csv")

In [20]:
df = pd.read_csv("Student.csv")
df.head()

   Unnamed: 0  Student  Age  Marks
0           0     Aman   30     95
1           1  Shardha   28     90
2           2   Raghav   26     60
3           3    Alakh   35     97
4           4  Striver   45     45

In [21]:
df = pd.read_csv("AiTrends.csv")
df.head()

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2

In [24]:
data = {
    "Name": ["Aman", "Riya", "Karan"],
    "City": ["Delhi", "Mumbai", "Pune"],
    "Salary": [30000, 40000, 35000]
}
df = pd.DataFrame(data)
df.to_csv("Comma.csv", index=False)

In [30]:
df

    Name    City  Salary
0   Aman   Delhi   30000
1   Riya  Mumbai   40000
2  Karan    Pune   35000

In [34]:
df = pd.read_csv("Comma.csv")
df

    Name    City  Salary
0   Aman   Delhi   30000
1   Riya  Mumbai   40000
2  Karan    Pune   35000

In [38]:
df = pd.read_csv("Comma.csv", usecols=['Name','City'])
df

    Name    City
0   Aman   Delhi
1   Riya  Mumbai
2  Karan    Pune